config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.

  devise_for :users

  devise_scope :user do
    authenticated :user do
      root 'posts#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  root to: "devise/sessions#new"

  resources :posts do
    resources :likes, only: [:create, :destroy]
  end

  get "up" => "rails/health#show", as: :rails_health_check

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :user_id, uniqueness: { scope: :post_id }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :likes
  has_many :liked_posts, through: :likes, source: :post
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
  
    private
  
    # Redirect authenticated users from the Devise sign-in page
    def after_sign_in_path_for(resource)
        posts_path # Assuming you have set up a home#index as the landing page after login
    end
  end
  

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :authenticate_user!
  
  def create
    @post = Post.find(params[:post_id])
    @post.likes.create(user: current_user)
    redirect_to posts_path, notice: "You liked the post!"
  end

  def destroy
    @post = Post.find(params[:post_id])
    @like = @post.likes.find(params[:id])
    @like.destroy
    redirect_to posts_path, notice: "You unliked the post."
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def show
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to posts_path, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to posts_path, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path, notice: 'Post was successfully destroyed.'
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  before_action :redirect_if_authenticated, only: [:new, :create]

  private

  def redirect_if_authenticated
    redirect_to posts_path, notice: 'You are already signed in.' if user_signed_in?
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def display_form_error_messages(resource, field_name)
        if resource.errors.any? && resource.errors.messages[field_name].any?
          content_tag(:div, class: 'error-messages alert alert-danger') do
            resource.errors.full_messages_for(field_name).join(', ')
          end
        end
      end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<div class="container mt-5">
  <h1>Edit Post</h1>
  <%= form_with(model: @post, local: true, html: { class: 'form' }) do |form| %>
    <div class="mb-3">
      <%= form.label :title, class: 'form-label' %>
      <%= form.text_field :title, class: 'form-control', required: true %>
      <%= display_form_error_messages(@post, :title) %>
    </div>
    <div class="mb-3">
      <%= form.label :content, class: 'form-label' %>
      <%= form.text_area :content, class: 'form-control', rows: 5, required: true %>
      <%= display_form_error_messages(@post, :content) %>
    </div>
    <div class="actions">
      <%= form.submit 'Update Post', class: 'btn btn-success' %>
      <%= link_to 'Back to Posts', posts_path, class: 'btn btn-link' %>
    </div>
  <% end %>
</div>

app/views/posts/index.html.erb
<div class="container mt-5">
  <h1>Posts</h1>
  <%= link_to 'Create New Post', new_post_path, class: 'btn btn-primary mb-3' %>

  <table class="table table-bordered">
    <thead class="thead-dark">
      <tr>
        <th>Title</th>
        <th>Content</th>
        <th>Likes</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @posts.each do |post| %>
        <tr>
          <td><%= post.title %></td>
          <td><%= post.content %></td>
          <td>
            <%= post.likes.count %>
            <% if post.likes.find_by(user: current_user) %>
              <%= link_to 'Unlike', post_like_path(post, post.likes.find_by(user: current_user)),
                          method: :delete, class: 'btn btn-outline-danger btn-sm' %>
            <% else %>
              <%= link_to 'Like', post_likes_path(post), method: :post, class: 'btn btn-outline-primary btn-sm' %>
            <% end %>
          </td>
          <td>
            <%= link_to 'Edit', edit_post_path(post), class: 'btn btn-warning btn-sm' %>
            <%= link_to 'Delete', post_path(post), method: :delete, data: { confirm: 'Are you sure?' },
                        class: 'btn btn-danger btn-sm' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <% if user_signed_in? %>
    <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'btn btn-secondary' %>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="container mt-5">
  <h1>New Post</h1>
  <%= form_with(model: @post, local: true, html: { class: 'form' }) do |form| %>
    <div class="mb-3">
      <%= form.label :title, class: 'form-label' %>
      <%= form.text_field :title, class: 'form-control', placeholder: 'Enter title', required: true %>
      <%= display_form_error_messages(@post, :title) %>
    </div>
    <div class="mb-3">
      <%= form.label :content, class: 'form-label' %>
      <%= form.text_area :content, class: 'form-control', placeholder: 'Enter content', rows: 5, required: true %>
      <%= display_form_error_messages(@post, :content) %>
    </div>
    <div class="actions">
      <%= form.submit 'Create Post', class: 'btn btn-primary' %>
      <%= link_to 'Back to Posts', posts_path, class: 'btn btn-link' %>
    </div>
  <% end %>
</div>